# Generated by Django 4.0.1 on 2022-01-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelingMechanic', '0002_commission_askprice_commission_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='lat',
            field=models.IntegerField(default=-82.374),
        ),
        migrations.AddField(
            model_name='commission',
            name='long',
            field=models.IntegerField(default=29.648),
        ),
    ]
