# Generated by Django 4.0.1 on 2022-01-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelingMechanic', '0005_rename_reviews_webuser_rating_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reviews',
            new_name='review',
        ),
    ]
