# Generated by Django 4.0.1 on 2022-01-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelingMechanic', '0006_rename_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='profilePic',
            field=models.ImageField(default='default.png', upload_to='profilePic'),
        ),
    ]
