# Generated by Django 4.0.1 on 2022-01-29 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelingMechanic', '0007_webuser_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='askPrice',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='commission',
            name='lat',
            field=models.FloatField(default=-82.374),
        ),
        migrations.AlterField(
            model_name='commission',
            name='long',
            field=models.FloatField(default=29.648),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
