# Generated by Django 4.0.1 on 2022-01-29 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelingMechanic', '0009_alter_webuser_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taker_requests_created', to='travelingMechanic.webuser'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_requests_created', to='travelingMechanic.webuser'),
        ),
    ]
