# Generated by Django 4.0.1 on 2022-01-30 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelingMechanic', '0010_commission_taker_alter_commission_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review_author_requests_created', to='travelingMechanic.webuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_requests_created', to='travelingMechanic.webuser'),
        ),
    ]
